version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00" # UTC
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"  # Group all updates into a single larger pull request.

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00" # UTC
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: "docker"
    directory: "/build"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "12:00" # UTC
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "alpine"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    ignore:
      - dependency-name: "golang"
        update-types: # update only digests
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      docker:
        patterns:
          - "*"  # Group all updates into a single larger pull request.
