extends: "@commitlint/config-conventional"
rules:
  type-enum:
    - 2
    - always
    -
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - gen
      - perf
      - refactor
      - renovate
      - revert
      - sec
      - style
      - test
