# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: geomixer

report_sizes: true

before:
  hooks:
    - go mod tidy

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - id: geomixer
    main: .
    binary: geomixer
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
  algorithm: sha256
  split: false

docker_digest:
  disable: true

sboms:
  - id: archive
    artifacts: archive

changelog:
  disable: false
  use: github
  format: "{{.SHA}}: {{.Message}}{{ if .Logins }} ({{ .Logins | englishJoin }}){{ end }}"
  sort: asc
  abbrev: 7
  groups:
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Security"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 2
    - title: "Renovate"
      regexp: ^.*?renovate?(\(.+\))??!?:.+$
      order: 3
    - title: "Documentation"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 4
    - title: "Misc"
      order: 5
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: typo$"
      - "merge conflict"
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers_v2:
  - id: geomixer
    disable: true

signs:
  - cmd: cosign
    signature: "${artifact}.sigstore.json"
    output: true
    artifacts: checksum
    args:
      - sign-blob
      - "--bundle=${signature}"
      - "${artifact}"
      - --yes

# docker_signs:
#   - cmd: cosign
#     artifacts: manifests
#     output: true
#     args:
#       - "sign"
#       - "${artifact}@${digest}"
#       - --yes

release:
  disable: false
  draft: false
  skip_upload: false
  name_template: "v{{ .Version }}"
  mode: replace
  header: |
    ## {{.ProjectName}} {{.Version}} ({{.Date}})
