# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: geomixer

builds:
  - id: geomixer
    main: .
    binary: geomixer
    ldflags:
      - -s -w -extldflags "-static"
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - arm64
      - amd64

sboms:
  - id: archive
    artifacts: archive

archives:
  - formats: [ 'tar.gz' ]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    files:
      - LICENSE
      - README.md

snapshot:
  version_template: SNAPSHOT-{{ .Commit }}

checksum:
  disable: false
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"
  algorithm: sha256
  split: false

docker_digest:
  disable: true

changelog:
  disable: false
  use: github
  sort: asc
  abbrev: 7
  groups:
    - title: "Features"
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: "Security"
      regexp: '^.*?sec(\(.+\))??!?:.+$'
      order: 1
    - title: "Bug fixes"
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 2
    - title: "Renovate"
      regexp: ^.*?renovate?(\(.+\))??!?:.+$
      order: 3
    - title: "Documentation"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 4
    - title: "Misc"
      order: 5
  filters:
    exclude:
      - "^test:"
      - "^test\\("
      - "^chore: typo$"
      - "merge conflict"
      - Merge pull request
      - Merge branch
      - go mod tidy

release:
  disable: false
  name_template: "v{{ .Version }}"
  mode: replace

  header: |
    ## {{.ProjectName}} {{.Version}} ({{.Date}})

  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-source'
