// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: internal/geosite/geosite.proto

package geosite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of domain value.
type Domain_Type int32

const (
	// The value is used as a sub string.
	Domain_substr Domain_Type = 0
	// The value is used as a regular expression.
	Domain_regex Domain_Type = 1
	// The value is a domain.
	Domain_domain Domain_Type = 2
	// The value is a full domain.
	Domain_full Domain_Type = 3
)

// Enum value maps for Domain_Type.
var (
	Domain_Type_name = map[int32]string{
		0: "substr",
		1: "regex",
		2: "domain",
		3: "full",
	}
	Domain_Type_value = map[string]int32{
		"substr": 0,
		"regex":  1,
		"domain": 2,
		"full":   3,
	}
)

func (x Domain_Type) Enum() *Domain_Type {
	p := new(Domain_Type)
	*p = x
	return p
}

func (x Domain_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Domain_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_geosite_geosite_proto_enumTypes[0].Descriptor()
}

func (Domain_Type) Type() protoreflect.EnumType {
	return &file_internal_geosite_geosite_proto_enumTypes[0]
}

func (x Domain_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Domain_Type.Descriptor instead.
func (Domain_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{0, 0}
}

type Domain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain matching type.
	Type Domain_Type `protobuf:"varint,1,opt,name=type,proto3,enum=internal.geosite.Domain_Type" json:"type,omitempty"`
	// Domain value.
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// Attributes of this domain. May be used for filtering.
	Attributes    []*Domain_Attribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetType() Domain_Type {
	if x != nil {
		return x.Type
	}
	return Domain_substr
}

func (x *Domain) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Domain) GetAttributes() []*Domain_Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Domains       []*Domain              `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{1}
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

type GeoSite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoSite) Reset() {
	*x = GeoSite{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoSite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoSite) ProtoMessage() {}

func (x *GeoSite) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoSite.ProtoReflect.Descriptor instead.
func (*GeoSite) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{2}
}

func (x *GeoSite) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type Domain_Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to TypedValue:
	//
	//	*Domain_Attribute_BoolValue
	//	*Domain_Attribute_IntValue
	TypedValue    isDomain_Attribute_TypedValue `protobuf_oneof:"typed_value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain_Attribute) Reset() {
	*x = Domain_Attribute{}
	mi := &file_internal_geosite_geosite_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain_Attribute) ProtoMessage() {}

func (x *Domain_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_internal_geosite_geosite_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain_Attribute.ProtoReflect.Descriptor instead.
func (*Domain_Attribute) Descriptor() ([]byte, []int) {
	return file_internal_geosite_geosite_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Domain_Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Domain_Attribute) GetTypedValue() isDomain_Attribute_TypedValue {
	if x != nil {
		return x.TypedValue
	}
	return nil
}

func (x *Domain_Attribute) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.TypedValue.(*Domain_Attribute_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Domain_Attribute) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.TypedValue.(*Domain_Attribute_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

type isDomain_Attribute_TypedValue interface {
	isDomain_Attribute_TypedValue()
}

type Domain_Attribute_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Domain_Attribute_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=int_value,json=intValue,proto3,oneof"`
}

func (*Domain_Attribute_BoolValue) isDomain_Attribute_TypedValue() {}

func (*Domain_Attribute_IntValue) isDomain_Attribute_TypedValue() {}

var File_internal_geosite_geosite_proto protoreflect.FileDescriptor

const file_internal_geosite_geosite_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/geosite/geosite.proto\x12\x10internal.geosite\"\xb8\x02\n" +
	"\x06Domain\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.internal.geosite.Domain.TypeR\x04type\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12B\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\".internal.geosite.Domain.AttributeR\n" +
	"attributes\x1al\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x03 \x01(\x03H\x00R\bintValueB\r\n" +
	"\vtyped_value\"3\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06substr\x10\x00\x12\t\n" +
	"\x05regex\x10\x01\x12\n" +
	"\n" +
	"\x06domain\x10\x02\x12\b\n" +
	"\x04full\x10\x03\"R\n" +
	"\bCategory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x122\n" +
	"\adomains\x18\x02 \x03(\v2\x18.internal.geosite.DomainR\adomains\"E\n" +
	"\aGeoSite\x12:\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1a.internal.geosite.CategoryR\n" +
	"categoriesB.Z,github.com/KazZzeL/geomixer/internal/geositeb\x06proto3"

var (
	file_internal_geosite_geosite_proto_rawDescOnce sync.Once
	file_internal_geosite_geosite_proto_rawDescData []byte
)

func file_internal_geosite_geosite_proto_rawDescGZIP() []byte {
	file_internal_geosite_geosite_proto_rawDescOnce.Do(func() {
		file_internal_geosite_geosite_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_geosite_geosite_proto_rawDesc), len(file_internal_geosite_geosite_proto_rawDesc)))
	})
	return file_internal_geosite_geosite_proto_rawDescData
}

var file_internal_geosite_geosite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_geosite_geosite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_geosite_geosite_proto_goTypes = []any{
	(Domain_Type)(0),         // 0: internal.geosite.Domain.Type
	(*Domain)(nil),           // 1: internal.geosite.Domain
	(*Category)(nil),         // 2: internal.geosite.Category
	(*GeoSite)(nil),          // 3: internal.geosite.GeoSite
	(*Domain_Attribute)(nil), // 4: internal.geosite.Domain.Attribute
}
var file_internal_geosite_geosite_proto_depIdxs = []int32{
	0, // 0: internal.geosite.Domain.type:type_name -> internal.geosite.Domain.Type
	4, // 1: internal.geosite.Domain.attributes:type_name -> internal.geosite.Domain.Attribute
	1, // 2: internal.geosite.Category.domains:type_name -> internal.geosite.Domain
	2, // 3: internal.geosite.GeoSite.categories:type_name -> internal.geosite.Category
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_geosite_geosite_proto_init() }
func file_internal_geosite_geosite_proto_init() {
	if File_internal_geosite_geosite_proto != nil {
		return
	}
	file_internal_geosite_geosite_proto_msgTypes[3].OneofWrappers = []any{
		(*Domain_Attribute_BoolValue)(nil),
		(*Domain_Attribute_IntValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_geosite_geosite_proto_rawDesc), len(file_internal_geosite_geosite_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_geosite_geosite_proto_goTypes,
		DependencyIndexes: file_internal_geosite_geosite_proto_depIdxs,
		EnumInfos:         file_internal_geosite_geosite_proto_enumTypes,
		MessageInfos:      file_internal_geosite_geosite_proto_msgTypes,
	}.Build()
	File_internal_geosite_geosite_proto = out.File
	file_internal_geosite_geosite_proto_goTypes = nil
	file_internal_geosite_geosite_proto_depIdxs = nil
}
