name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: {}

env: {}
defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  queue: single

jobs:
  lint:
    name: Lint
    permissions:
      contents: read # inherit from lint.yml
    if: ${{ !cancelled() }}
    uses: $/.github/workflows/lint.yml
    with:
      report_name: ${{ vars.LINT_REPORT || 'lint-report' }}

  test:
    name: Test
    permissions:
      contents: read # inherit from test.yml
    if: ${{ !cancelled() }}
    uses: $/.github/workflows/test.yml
    with:
      test_report_name: ${{ vars.TEST_REPORT || 'test-report' }}
      cvrg_report_name: ${{ vars.CVRG_REPORT || 'cvrg-report' }}
      cvrg_report_ttl: ${{ github.ref == 'refs/heads/master' && 90 || -1 }}

  leak:
    name: Leak
    permissions:
      contents: read # inherit from leak.yml
    if: ${{ !cancelled() }}
    uses: $/.github/workflows/leak.yml
    with:
      report_name: ${{ vars.LEAK_REPORT || 'leak-report' }}
